// F19 (P2-W15): the frozen MCP decisions. Every value here is pinned by test/mcp/policy.test.js; the tool list itself is never
// written by hand, it is projected from the command manifest (project.js) under these rules.

function deepFreeze(value) {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value)) deepFreeze(child);
  }
  return value;
}

export const MCP_SERVER_NAME = 'akrs';

// Dual era (A1 6.1): an `initialize` request selects legacy semantics for the life of the process; a request whose `_meta` names a
// protocol version is served statelessly by the 2026-07-28 rules. Both may arrive on the same process.
export const MCP_PROTOCOL = deepFreeze({
  modern_versions: ['2026-07-28'],
  legacy_versions: ['2025-11-25', '2025-06-18', '2025-03-26'],
  // a legacy client asking for an unknown version gets the newest legacy version (it may then disconnect)
  legacy_fallback: '2025-11-25',
  meta_keys: {
    protocol_version: 'io.modelcontextprotocol/protocolVersion',
    client_capabilities: 'io.modelcontextprotocol/clientCapabilities',
    client_info: 'io.modelcontextprotocol/clientInfo',
    server_info: 'io.modelcontextprotocol/serverInfo',
  },
  capabilities: { tools: { listChanged: false } },
  // modern: every result carries resultType; cacheable results (tools/list, server/discover) carry ttlMs and cacheScope
  result_type: 'complete',
  cache: { ttl_ms: 3_600_000, scope: 'public' },
  methods: {
    legacy: ['initialize', 'ping', 'tools/call', 'tools/list'],
    modern: ['server/discover', 'tools/call', 'tools/list'],
    notifications: ['notifications/cancelled', 'notifications/initialized'],
  },
});

// JSON-RPC error mapping. A packet (ok, warning, blocked, error findings) is always a tool RESULT; only protocol faults are errors.
export const MCP_ERRORS = deepFreeze({
  parse_error: -32700,
  invalid_request: -32600,
  method_not_found: -32601,
  invalid_params: -32602, // unknown tool name, malformed tools/call params
  internal_error: -32603,
  unsupported_protocol_version: -32022, // modern request naming an unsupported version, or no version and no legacy session
});

// Packet -> tool result: the CLI exit code decides isError. 0 and 1 (ok, noop, findings, blocked) are successful tool results carrying the
// status; 2 (usage, including rejected MCP arguments), 3 (workflow missing) and 4 (internal) are tool errors carrying the finding code.
export const MCP_RESULT_POLICY = deepFreeze({
  is_error_exit_codes: [2, 3, 4],
  usage_finding: 'AKRS-C001',
  // the text block is the prompt rendering; above this many UTF-8 bytes it is written to the cache and the text names the file
  text_cap_bytes: 16_384,
  overflow_directory: '.cache/mcp',
  structured_content: 'always the complete packet, equal to `akrs <command> --json` for the same input',
});

// The flat-schema subset (A1 6.2): names, the only types, and the keywords a schema may use.
export const MCP_SCHEMA_RULES = deepFreeze({
  max_tools: 7,
  tool_name_pattern: '^[a-z][a-z0-9_]{0,29}$',
  argument_name_pattern: '^[a-z][a-z0-9_]{0,63}$',
  property_types: ['string', 'integer', 'boolean', 'array'],
  array_items: 'string',
  tool_keys: ['description', 'inputSchema', 'name'],
  schema_keys: ['additionalProperties', 'properties', 'required', 'type'],
  property_keys: ['description', 'enum', 'items', 'type'],
  forbidden_keywords: ['$ref', '$schema', 'allOf', 'anyOf', 'const', 'default', 'format', 'not', 'oneOf'],
  description_max_chars: 200,
});

// Manifest -> tool projection. One tool per distinct `mcp_tool`, one `action` enum value per `mcp_action`, in manifest order. Every
// positional and flag of an action becomes a flat argument (snake_case of its name) except the excluded ones; the server adds the
// root flags it was started with to every call.
export const MCP_PROJECTION = deepFreeze({
  action_argument: 'action',
  // output is fixed (packet + prompt), roots are the server's, request IDs are generated by the CLI (A1 AX2 / Lock 19)
  excluded_flags: ['--json', '--jsonl', '--prompt', '--request-id', '--root', '--workflow-root'],
  // A1 4 / 6.2: structured input travels as a contained draft path
  renamed_flags: { '--input': 'input_path' },
  // per-tool positional names (A1 6.2 argument table); a list is tried in order and the first argument given wins
  positional_aliases: {
    akrs_scope: { target: ['request', 'road'] },
    akrs_status: { code: ['id'] },
    akrs_write: { plan: ['id'], road: ['id'] },
  },
  value_types: { boolean: 'boolean', integer: 'integer', path: 'string', string: 'string' },
  tool_purposes: {
    akrs_page: 'Read a running web page through an installed browser (untrusted data).',
    akrs_road: 'Road queries: the Worker or Leader packet, route fit, templates, checks and readiness.',
    akrs_scope: 'Scope requests: ask for more reads or writes, approve, reject or list them.',
    akrs_status: 'Workflow state: status, next commands, validation, finding explanations, graph and the Leader boot packet.',
    akrs_test: 'Tester loop: the Plan Tester packet, the scenario run, the result and Worker handoffs.',
    akrs_work: 'Worker loop: claim a Road (work), finish it in one call (done) or give it back (yield).',
    akrs_write: 'Leader writes: Roads, Tasks, Memory, State, executors, verification contracts, activation and Plan close.',
  },
});

// Server-side argument coercion for weak and Chinese-model tool callers (A1 6.2, agent matrix).
export const MCP_COERCION = deepFreeze({
  null: 'a null argument counts as absent',
  boolean: 'true/false, or the strings "true"/"false"',
  integer: 'a safe integer, or a string of decimal digits with an optional leading minus',
  array: 'an array of strings, a string holding a JSON array of strings, or one plain string (one element)',
  path: 'one leading "@" is removed from a path argument (input_path and every path-typed flag)',
  string: 'strings only; anything else is rejected',
  rejected: 'an unknown argument, an argument the action does not take, a missing required argument or a value of the wrong type is a tool error with AKRS-C001',
});

export const MCP_CANCELLATION = deepFreeze({
  notification: 'notifications/cancelled',
  rule: 'tool calls run one at a time in arrival order; a cancelled queued call never runs, a running call has its abort signal raised (test run ends its app and browser and writes nothing) and no response is sent for a cancelled request',
  shutdown: 'stdin end: every request already received is still answered, but the abort signal of every pending call is raised so an execution (test run) ends early with an interrupted packet; stdout is drained and the process ends without process.exit()',
});

// stdio framing: UTF-8, one JSON-RPC message per line, a trailing CR and a leading BOM tolerated, protocol bytes only on stdout.
export const MCP_FRAMING = deepFreeze({
  delimiter: '\n',
  max_line_bytes: 4 * 1024 * 1024,
  stdout: 'JSON-RPC messages only; console.log/info/debug are moved to stderr while serving',
  stderr: 'one start line, one stop line, and anything a handler prints',
});

export const MCP_INSTRUCTIONS = [
  'AKRS workflow tools. Each call returns the same packet as the akrs CLI with --json: read status, findings and next_commands, then do the next command.',
  'Worker: akrs_work work -> edit only the declared writes -> akrs_work done. Tester: akrs_test details -> run -> result.',
  'Leader: akrs_status boot, then akrs_write / akrs_scope.',
  'Never pass hashes, snapshots or request IDs. Structured input: write JSON to akrs/drafts/<name>.json, pass input_path.',
  'A large result names a file under akrs/.cache/mcp/ to read.',
].join(' ');
